"""Tests 2 and 3: cross-validation against vendor pyfrbus, and sanity signs.

The reference CSV in tests/data was generated by running the Fed's own
pyfrbus (vendor/pyfrbus_package, with relaxed dependency pins and its Newton
solver at xtol=1e-8) on the identical experiment; see VALIDATION.md.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

START = pd.Period("2026Q1")
END = pd.Period("2030Q4")
VENDOR_CSV = Path(__file__).parent / "data" / "vendor_shock_2026q1_2030q4.csv"


@pytest.fixture(scope="module")
def shock_sim(model, longbase):
    data = longbase.copy()
    # Demo fiscal configuration: surplus-ratio targeting
    data.loc[START:END, "dfpdbt"] = 0
    data.loc[START:END, "dfpsrp"] = 1
    with_adds = model.init_trac(START, END, data)
    with_adds.loc[START, "rffintay_aerr"] += 1  # 100bp funds-rate shock
    sim = model.solve(START, END, with_adds)
    return with_adds, sim


def test_cross_validation_vs_pyfrbus(model, shock_sim):
    """Test 2: full-vector comparison against the Fed's pyfrbus."""
    _, sim = shock_sim
    vendor = pd.read_csv(VENDOR_CSV, index_col=0)
    vendor.index = pd.PeriodIndex(vendor.index, freq="Q")

    ours = sim.loc[START:END, vendor.columns]
    abs_diff = (ours - vendor).abs().to_numpy()
    rel_diff = abs_diff / np.maximum(np.abs(vendor.to_numpy()), 1e-8)

    assert np.nanmax(abs_diff) < 1e-6
    assert np.nanmax(rel_diff) < 1e-6


def test_sanity_signs(shock_sim):
    """Test 3: monetary tightening lowers output and inflation, raises lur."""
    base, sim = shock_sim
    rff_delta = sim.loc[START:END, "rff"] - base.loc[START:END, "rff"]
    gdp_pct = 100 * (sim.loc[START:END, "xgdp"] / base.loc[START:END, "xgdp"] - 1)
    lur_delta = sim.loc[START:END, "lur"] - base.loc[START:END, "lur"]
    pi_delta = sim.loc[START:END, "picxfe"] - base.loc[START:END, "picxfe"]

    # Funds rate rises ~1pp on impact
    assert 0.8 < rff_delta.iloc[0] < 1.2
    # Output falls, with a trough between -0.2% and -1.2% (FRB/US VAR properties)
    assert -1.2 < gdp_pct.min() < -0.2
    # Unemployment rises
    assert 0.1 < lur_delta.max() < 0.6
    # Core inflation falls
    assert -0.15 < pi_delta.min() < -0.005
